In [21]:

import pandas as pd
data = {'name':['Kane','Suri','Sabin','Hellen','Eric'],
        'year':[971,984,990,987,970],
        'score':[10,20,30,40,50]}
df = pd.DataFrame(data,index=['K','S','Sb','H','E'])
print(df)
print('-' * 20)
print(df.loc['S','name'])
print(df.loc['Sb',['year','score']])
print('-' * 20)
print(df.iloc[0,0])
print(df.iloc[3,:1])
print(df.iloc[:,[0,2]])


    


      name  year  score
K     Kane   971     10
S     Suri   984     20
Sb   Sabin   990     30
H   Hellen   987     40
E     Eric   970     50
--------------------
Suri
year     990
score     30
Name: Sb, dtype: object
--------------------
Kane
name    Hellen
Name: H, dtype: object
      name  score
K     Kane     10
S     Suri     20
Sb   Sabin     30
H   Hellen     40
E     Eric     50


In [33]:
import numpy as np

data = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data)
print(data [0][1])
print(data[2][1:])
data[1][:]=10
print(data)
data[:][1]=120
print(data)
data[:]=3000
print(data)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[8 9]
[[ 1  2  3]
 [10 10 10]
 [ 7  8  9]]
[[  1   2   3]
 [120 120 120]
 [  7   8   9]]
[[3000 3000 3000]
 [3000 3000 3000]
 [3000 3000 3000]]


In [39]:
import numpy as np
dta = np.array([[5,7,9],[-7,-6,19],[6,8.9,11]])
print(dta)
A_inv = np.linalg.inv(dta)
print(A_inv)
multi = np.dot(dta,A_inv)
print(multi)


[[ 5.   7.   9. ]
 [-7.  -6.  19. ]
 [ 6.   8.9 11. ]]
[[ 3.12632979 -0.0412234  -2.48670213]
 [-2.53989362 -0.01329787  2.10106383]
 [ 0.34973404  0.03324468 -0.25265957]]
[[ 1.00000000e+00  2.08166817e-17  8.88178420e-16]
 [-2.77555756e-16  1.00000000e+00  0.00000000e+00]
 [ 2.38697950e-15  6.24500451e-17  1.00000000e+00]]
